name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: tsc & eslint & test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: test
        run: |
          yarn install
          yarn tsc
          yarn lint
          yarn test
